name = "RegisterUtilities"
uuid = "d4862ba2-f42c-5aeb-af4f-96a8884a16c4"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RegisterCore = "67712758-55e7-5c3c-8e85-dda1d7758434"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
